; Maker-ESP32 Pro onboard motor demo
; M0(27,13) M1(4,2) M2(17,12) M3(14,15)
; https://github.com/nulllaborg/maker-esp32-pro
; Official Arduino sample: motorTest.zip (same pins)

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = maker-esp32-pro

[env:maker-esp32-pro]
extends = common
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
board_build.flash_size = 4MB
