; MiniSumo_QT_PY_Pico_8x8_13x9_SCMD
; Source: Robots/MiniSumo/MiniSumo_QT_PY_Pico_8x8_13x9_SCMD
; https://github.com/dancingevilgenius/Robots.git

[platformio]
extra_configs = ../../../platformio.shared.ini
default_envs = adafruit_qtpy_esp32pico

[env:adafruit_qtpy_esp32pico]
extends = common
platform = espressif32
board = adafruit_qtpy_esp32
framework = arduino
upload_speed = 921600
board_build.flash_size = 8MB
board_build.psram = enabled
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv

build_flags =
    -DCORE_DEBUG_LEVEL=0
